name: Flutter Web Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      # Install dependencies (including dev dependencies)
      - name: Install Dependencies
        run: |
          flutter pub get
          flutter pub add dev:build_runner --dev

      # Only run build_runner if needed (for projects using code generation)
      - name: Run Build Runner (if needed)
        run: |
          if grep -q "build_runner" pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          else
            echo "No build_runner dependency found, skipping code generation"
          fi

      # Build the Flutter web app
      - name: Build Flutter Web
        run: |
          flutter build web \
            --release \
            --base-href /flutter_david_weijian_dashboard/ \
            --dart-define=FLUTTER_WEB_CANVASKIT_URL=/flutter_david_weijian_dashboard/canvaskit/

      # Handle routing
      - name: Handle Routing
        run: |
          cp build/web/index.html build/web/404.html
          sed -i 's/<base href="\/flutter_david_weijian_dashboard\/">/<base href="\/">/g' build/web/404.html

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          publish_dir: ./build/web
          keep_files: false
